[program:frontend]
command=node /app/frontend/server.js
user=root
autostart=true
autorestart=true
priority=350
stdout_logfile=/var/log/supervisor/frontend.log
stderr_logfile=/var/log/supervisor/frontend_err.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
directory=/app/frontend
stopwaitsecs=30
environment=NODE_ENV="production",PORT="3000",HOSTNAME="0.0.0.0",NEXT_PUBLIC_API_URL="http://localhost:6002"
