[program:frontend]
command=npx next start -p 3000
user=root
autostart=true
autorestart=true
priority=350
stdout_logfile=/var/log/supervisor/frontend.log
stderr_logfile=/var/log/supervisor/frontend_err.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
directory=/app/frontend
stopwaitsecs=30
environment=NODE_ENV="production",NEXT_PUBLIC_API_URL="http://localhost:6002"
