[program:redis]
command=/usr/bin/redis-server /etc/redis/redis.conf
user=root
autostart=true
autorestart=true
priority=200
stdout_logfile=/var/log/supervisor/redis.log
stderr_logfile=/var/log/supervisor/redis_err.log
stdout_logfile_maxbytes=10MB
stderr_logfile_maxbytes=10MB
directory=/tmp
stopwaitsecs=10
