[program:worker]
command=node /app/backend/dist/workers/transcription.js
user=root
autostart=true
autorestart=true
priority=400
stdout_logfile=/var/log/supervisor/worker.log
stderr_logfile=/var/log/supervisor/worker_err.log
stdout_logfile_maxbytes=50MB
stderr_logfile_maxbytes=50MB
directory=/app/backend
stopwaitsecs=30
environment=NODE_ENV="production"
