import { Task, DateExtracted } from '@prisma/client';

export function exportToTxt(transcript: any, analysis: any, job: any): string {
  let content = '=' .repeat(60) + '\n';
  content += 'TRANSCRIBE AI - TRANSCRIPT & ANALYSIS\n';
  content += '=' .repeat(60) + '\n\n';

  content += `File: ${job.fileName}\n`;
  content += `Date: ${job.createdAt.toISOString().split('T')[0]}\n`;
  content += `Type: ${job.type}\n\n`;

  content += '-'.repeat(60) + '\n';
  content += 'TRANSCRIPT\n';
  content += '-'.repeat(60) + '\n\n';

  if (transcript?.text) {
    transcript.text.forEach((seg: any) => {
      const speaker = transcript.speakers?.find((s: any) => s.id === seg.speakerId);
      const time = formatTime(seg.start);
      content += `[${time}] ${speaker?.name || 'Unknown'}: ${seg.content}\n\n`;
    });
  }

  if (analysis) {
    content += '\n' + '-'.repeat(60) + '\n';
    content += 'ANALYSIS\n';
    content += '-'.repeat(60) + '\n\n';

    if (analysis.summary) {
      content += `SUMMARY\n${analysis.summary}\n\n`;
    }

    if (analysis.keyPoints?.length) {
      content += `KEY POINTS\n`;
      analysis.keyPoints.forEach((p: string, i: number) => {
        content += `${i + 1}. ${p}\n`;
      });
      content += '\n';
    }

    if (analysis.decisions?.length) {
      content += `DECISIONS\n`;
      analysis.decisions.forEach((d: string, i: number) => {
        content += `${i + 1}. ${d}\n`;
      });
      content += '\n';
    }

    if (analysis.risks?.length) {
      content += `RISKS\n`;
      analysis.risks.forEach((r: string, i: number) => {
        content += `${i + 1}. ${r}\n`;
      });
      content += '\n';
    }

    if (analysis.openQuestions?.length) {
      content += `OPEN QUESTIONS\n`;
      analysis.openQuestions.forEach((q: string, i: number) => {
        content += `${i + 1}. ${q}\n`;
      });
      content += '\n';
    }

    if (analysis.tasks?.length) {
      content += `TASKS\n`;
      analysis.tasks.forEach((t: any, i: number) => {
        content += `${i + 1}. ${t.description}`;
        if (t.owner) content += ` [${t.owner}]`;
        if (t.dueDate) content += ` - Due: ${new Date(t.dueDate).toLocaleDateString()}`;
        content += ` (${t.priority})\n`;
      });
      content += '\n';
    }
  }

  content += '=' .repeat(60) + '\n';
  content += 'Generated by Transcribe AI\n';

  return content;
}

export function exportToJson(transcript: any, analysis: any, job: any): string {
  return JSON.stringify({
    job: {
      id: job.id,
      fileName: job.fileName,
      createdAt: job.createdAt,
      type: job.type
    },
    transcript: transcript ? {
      language: transcript.language,
      duration: transcript.duration,
      speakers: transcript.speakers,
      segments: transcript.text
    } : null,
    analysis: analysis ? {
      summary: analysis.summary,
      keyPoints: analysis.keyPoints,
      decisions: analysis.decisions,
      risks: analysis.risks,
      openQuestions: analysis.openQuestions,
      tasks: analysis.tasks,
      dates: analysis.dates,
      mindmap: analysis.mindmap
    } : null
  }, null, 2);
}

export function generateTasksCsv(tasks: Task[]): string {
  const headers = ['Description', 'Owner', 'Priority', 'Status', 'Due Date'];
  const rows = tasks.map(t => [
    `"${t.description.replace(/"/g, '""')}"`,
    t.owner || '',
    t.priority,
    t.status,
    t.dueDate ? new Date(t.dueDate).toISOString().split('T')[0] : ''
  ]);

  return [headers.join(','), ...rows.map(r => r.join(','))].join('\n');
}

export function generateCalendar(dates: DateExtracted[], meetingTitle: string): string {
  const lines: string[] = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    'PRODID:-//Transcribe AI//Meeting Reminders//EN',
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    'X-WR-CALNAME:Transcribe AI - ' + meetingTitle
  ];

  dates.forEach((d, index) => {
    const startDate = new Date(d.date);
    const endDate = new Date(startDate);
    endDate.setHours(endDate.getHours() + 1);

    const uid = `${Date.now()}-${index}@transcribeai`;
    const dtstart = formatICSDate(startDate);
    const dtend = formatICSDate(endDate);
    const summary = d.description ? d.description.replace(/[,\n]/g, ' ') : meetingTitle;
    const description = `Extracted from ${meetingTitle} by Transcribe AI`;

    lines.push(
      'BEGIN:VEVENT',
      `UID:${uid}`,
      `DTSTAMP:${formatICSDate(new Date())}`,
      `DTSTART:${dtstart}`,
      `DTEND:${dtend}`,
      `SUMMARY:${summary}`,
      `DESCRIPTION:${description}`,
      'END:VEVENT'
    );
  });

  lines.push('END:VCALENDAR');

  return lines.join('\r\n');
}

function formatTime(seconds: number): string {
  const mins = Math.floor(seconds / 60);
  const secs = Math.floor(seconds % 60);
  return `${mins.toString().padStart(2, '0')}:${secs.toString().padStart(2, '0')}`;
}

function formatICSDate(date: Date): string {
  const iso = date.toISOString();
  return iso.replace(/[-:]/g, '').replace(/\.\d{3}/, '');
}
